# Get the GCC preinstalled image from Docker Hub
FROM openjdk:jdk-alpine

# Copy the current folder which contains C++ source code to the Docker image under /usr/src
COPY src/. /hello-java

# Specify the working directory
WORKDIR /hello-java

# Use GCC to compile the Test.cpp source file
RUN javac HelloJava.java

# Run the program output from the previous step
CMD ["java", "HelloJava"]
