# Get the GCC preinstalled image from Docker Hub
FROM gcc:9.3.0

# Copy the current folder which contains C++ source code to the Docker image under /usr/src
COPY src/. /hello-cpp

# Specify the working directory
WORKDIR /hello-cpp

# Use GCC to compile the Test.cpp source file
RUN g++ -o hello hello.cpp

# Run the program output from the previous step
CMD ["./hello"]
