# Get the GCC preinstalled image from Docker Hub
FROM mcr.microsoft.com/powershell:lts-alpine-3.10

# Copy the current folder which contains Elixir source code to the Docker image under /usr/src
COPY src/ /hello-powershell

# Specify the working directory
WORKDIR /hello-powershell

# Run the program output from the previous step
#CMD ["./Invoke-HelloPowershell.ps1"]
